// Generated by supabase_typegen 0.5.1 from GeneratorMetadata version 1.
// Do not edit by hand.
//
// Source schemas: public

// The typed table access API is still experimental.
// ignore_for_file: experimental_member_use

import 'package:supabase_flutter/supabase_flutter.dart';

/// A row of the `scores` table, as `select()` reads it with every column.
/// One row per pilot with their total round wins
extension type const ScoresRow(Map<String, dynamic> _json) implements Object {
  String get id => _json['id'] as String;
  String get name => _json['name'] as String;
  int get wins => _json['wins'] as int;
  DateTime get updatedAt => DateTime.parse(_json['updated_at'] as String);
  int get rounds => _json['rounds'] as int? ?? 0;
  int get kills => _json['kills'] as int? ?? 0;
  int get damage => _json['damage'] as int? ?? 0;
  int get shots => _json['shots'] as int? ?? 0;
  int get hits => _json['hits'] as int? ?? 0;
  int get survivalSeconds => _json['survival_seconds'] as int? ?? 0;

  /// The row as decoded from the response.
  Map<String, dynamic> toJson() => _json;
}

/// Values for inserting a row into `scores`. Columns that are nullable,
/// identity, or covered by a database default are optional; passing `null`
/// omits the column so the database default applies. Columns the database
/// always generates itself are left out entirely. Use the `set…ToNull` methods
/// to insert SQL NULL explicitly.
extension type const ScoresInsert._(Map<String, dynamic> _json)
    implements Object {
  ScoresInsert({
    required String id,
    required String name,
    int? wins,
    DateTime? updatedAt,
    int? rounds,
    int? kills,
    int? damage,
    int? shots,
    int? hits,
    int? survivalSeconds,
  }) : this._({
         'id': id,
         'name': name,
         'wins': ?wins,
         'updated_at': ?updatedAt?.toUtc().toIso8601String(),
         'rounds': ?rounds,
         'kills': ?kills,
         'damage': ?damage,
         'shots': ?shots,
         'hits': ?hits,
         'survival_seconds': ?survivalSeconds,
       });
}

/// Values for updating rows of `scores`. All columns are optional; passing
/// `null` omits the column, leaving it unchanged. Use the `set…ToNull` methods
/// to write SQL NULL explicitly.
extension type const ScoresUpdate._(Map<String, dynamic> _json)
    implements Object {
  ScoresUpdate({String? id, String? name, int? wins, DateTime? updatedAt})
    : this._({
        'id': ?id,
        'name': ?name,
        'wins': ?wins,
        'updated_at': ?updatedAt?.toUtc().toIso8601String(),
      });
}

/// Typed access to the `scores` table.
class Scores {
  const Scores._();

  /// Table definition for [PostgrestClient.table].
  static const table = PostgrestTable<ScoresRow, ScoresInsert, ScoresUpdate>(
    'scores',
    ScoresRow.new,
    schema: 'public',
    primaryKey: [id],
  );

  static const id = PostgrestColumn<ScoresRow, String>('id');
  static const name = PostgrestColumn<ScoresRow, String>('name');
  static const wins = PostgrestColumn<ScoresRow, int>('wins');
  static const updatedAt = PostgrestColumn<ScoresRow, DateTime>(
    'updated_at',
    fromJson: _dateTimeFromJson,
  );
}

DateTime _dateTimeFromJson(Object json) => DateTime.parse(json as String);
